# Generated by Django 4.1 on 2022-12-09 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloud_Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_prov_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flavor_name", models.CharField(max_length=64, unique=True)),
                ("CPU", models.CharField(blank=True, max_length=32, null=True)),
                ("Storage", models.CharField(blank=True, max_length=32, null=True)),
                ("Ram", models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image_name", models.CharField(max_length=64, unique=True)),
                ("Image_ID", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_provider", models.CharField(max_length=64, unique=True)),
                ("instance_name", models.CharField(max_length=64, unique=True)),
                ("team", models.CharField(max_length=64, unique=True)),
                ("program", models.CharField(max_length=64, unique=True)),
                ("Image", models.CharField(max_length=64, unique=True)),
                ("KeyName", models.CharField(max_length=64, unique=True)),
                ("flavor", models.CharField(max_length=64, unique=True)),
                ("users", models.CharField(max_length=64, unique=True)),
                ("contact", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(max_length=64, unique=True)),
                ("key_name_ID", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=64, unique=True)),
                ("budget", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=64, unique=True)),
                ("role_type", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=64, unique=True)),
                ("program_name", models.CharField(max_length=64, unique=True)),
                ("point_of_contact", models.CharField(max_length=64, unique=True)),
                ("network_code", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=64, unique=True)),
                ("team_name", models.CharField(max_length=64, unique=True)),
                ("employee_number", models.CharField(max_length=64, unique=True)),
                ("email", models.CharField(max_length=64, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("user_role", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
