# Generated by Django 4.1 on 2022-12-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.RemoveField(model_name="user", name="password",),
        migrations.RemoveField(model_name="user", name="username",),
    ]
