# Generated by Django 4.1 on 2022-12-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="flavor_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="instance",
            name="cloud_provider",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="instance", name="flavor", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="instance", name="team", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="role", name="role_name", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="role", name="role_type", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="team",
            name="network_code",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="team",
            name="point_of_contact",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="team",
            name="program_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="team", name="team_name", field=models.CharField(max_length=64),
        ),
    ]
