# Generated by Django 4.1 on 2022-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_flavor_flavor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance", name="users", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=64),
        ),
    ]
