# Generated by Django 4.1 on 2022-12-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_instance_users_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="KeyName",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="key", name="key_name", field=models.CharField(max_length=64),
        ),
    ]
