# Generated by Django 4.1 on 2022-12-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_instance_keyname_alter_key_key_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image", name="Image_ID", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="image",
            name="Image_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="instance", name="Image", field=models.CharField(max_length=64),
        ),
    ]
