# Generated by Django 4.1 on 2023-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_instance_program_alter_program_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="id_instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_instance_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="instance",
            name="id_instance",
            field=models.CharField(default=67, max_length=64),
            preserve_default=False,
        ),
    ]
