# Generated by Django 4.1 on 2023-01-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_id_instance_instance_id_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="flavor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.flavor"
            ),
        ),
    ]
