# Generated by Django 4.1 on 2023-01-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_instance_flavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="id_instance",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
