# Generated by Django 4.1 on 2023-01-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_instance_flavor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="flavor",
            field=models.ForeignKey(
                default=78,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.flavor",
            ),
            preserve_default=False,
        ),
    ]
