# Generated by Django 4.1 on 2023-01-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_instance_flavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="flavor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.flavor",
            ),
        ),
    ]
