# Generated by Django 4.1 on 2023-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_flavor_flavor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="flavor_name",
            field=models.CharField(max_length=64),
        ),
    ]
