# Generated by Django 4.1 on 2023-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_flavor_flavor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="launch_time",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
