# Generated by Django 4.1 on 2023-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_instance_launch_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Openstack_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image_name", models.CharField(max_length=64)),
                ("Image_ID", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Openstack_Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Openstack_Network_name", models.CharField(max_length=64)),
                ("Openstack_Network_id", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="flavor",
            name="id_flavor",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="network",
            field=models.CharField(default=4, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instance",
            name="openstack_flavor_id",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
