# Generated by Django 4.1 on 2023-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0019_openstack_image_openstack_network_flavor_id_flavor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="network",
            field=models.CharField(max_length=64),
        ),
    ]
