# Generated by Django 4.1 on 2023-01-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_instance_network"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openstack_image",
            old_name="Image_name",
            new_name="Openstack_image_name",
        ),
    ]
