# Generated by Django 4.1 on 2023-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_rename_image_name_openstack_image_openstack_image_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_name", models.CharField(max_length=64)),
                ("start_date", models.CharField(max_length=64)),
                ("end_date", models.CharField(max_length=64)),
                ("program", models.CharField(max_length=64)),
                ("team", models.CharField(max_length=64)),
                ("total_cost", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="instance",
            name="network",
            field=models.CharField(max_length=64),
        ),
    ]
