# Generated by Django 4.1 on 2023-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_bill_alter_instance_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="Unit",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
