# Generated by Django 4.1 on 2023-02-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_bill_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.program",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.team",
            ),
        ),
    ]
