# Generated by Django 4.1 on 2023-02-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_instance_program_alter_instance_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="program_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.program",
            ),
        ),
    ]
