# Generated by Django 4.1 on 2023-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
