# Generated by Django 4.1 on 2023-02-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_userprofile_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="team_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.team",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="network",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
