# Generated by Django 4.1 on 2023-02-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_rename_openstack_flavor_id_instance_id_flavour"),
    ]

    operations = [
        migrations.DeleteModel(name="id_instance",),
        migrations.DeleteModel(name="Openstack_Network",),
        migrations.AlterField(
            model_name="instance",
            name="KeyName",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.key",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="cloud_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.cloud_provider",
            ),
        ),
    ]
