# Generated by Django 4.1 on 2023-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_delete_id_instance_delete_openstack_network_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="contact",
            field=models.CharField(max_length=64),
        ),
    ]
