# Generated by Django 4.1 on 2023-02-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_instance_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.instance",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.program",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.team",
            ),
        ),
    ]
