# Generated by Django 4.1 on 2023-02-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_bill_bill_name_alter_bill_program_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bill", name="bill_name",),
    ]
