# Generated by Django 4.1 on 2023-02-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_remove_bill_bill_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.instance",
            ),
        ),
    ]
