# Generated by Django 4.1 on 2023-02-11 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_bill_bill_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance_snap_ind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(editable=False)),
                ("hash_key", models.CharField(default=None, max_length=64)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="snapshot_instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=64)),
                ("Image", models.CharField(max_length=64)),
                ("id_instance", models.CharField(max_length=64, unique=True)),
                ("launch_time", models.CharField(max_length=64, null=True)),
                ("id_flavour", models.CharField(max_length=64, null=True)),
                (
                    "KeyName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.key",
                    ),
                ),
                (
                    "cloud_provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.cloud_provider",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.flavor",
                    ),
                ),
                (
                    "instance_snap_index_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.instance_snap_ind",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.program",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.team",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
