# Generated by Django 4.1 on 2023-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_instance_snap_ind_snapshot_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot_instance",
            name="KeyName",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="cloud_provider",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="flavor",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="id_instance",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="program",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="team",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="snapshot_instance",
            name="users",
            field=models.CharField(max_length=64),
        ),
    ]
