# Generated by Django 4.1 on 2023-02-11 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_alter_snapshot_instance_keyname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot_instance",
            name="instance_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=64
            ),
            preserve_default=False,
        ),
    ]
