# Generated by Django 4.1 on 2023-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_alter_snapshot_instance_flavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot_instance",
            name="flavor",
            field=models.CharField(max_length=64),
        ),
    ]
