# Generated by Django 4.1 on 2023-02-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_snapshot_instance_cpu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.instance",
            ),
        ),
    ]
