# Generated by Django 4.1 on 2023-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_daily_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=56, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot_instance",
            name="daily_cost",
            field=models.DecimalField(decimal_places=2, default=56, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot_instance",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=56, max_digits=10),
            preserve_default=False,
        ),
    ]
