# Generated by Django 4.1 on 2023-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_alter_snapshot_instance_cpu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot_instance",
            name="daily_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
