# Generated by Django 4.1 on 2023-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_alter_snapshot_instance_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
