# Generated by Django 4.1 on 2023-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_alter_bill_unit"),
    ]

    operations = [
        migrations.RenameField(model_name="flavor", old_name="Ram", new_name="Ram_MB",),
        migrations.RenameField(
            model_name="flavor", old_name="Storage", new_name="Storage_GB",
        ),
        migrations.AlterField(
            model_name="instance_snap_ind",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
