# Generated by Django 4.1 on 2023-02-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_rename_ram_flavor_ram_mb_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="instance", name="Image",),
        migrations.AddField(
            model_name="instance",
            name="Image_aws",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.image",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="Image_op",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.openstack_image",
            ),
        ),
    ]
