# Generated by Django 4.1 on 2023-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_op_image_alter_instance_image_op_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="State",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot_instance",
            name="State",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
