# Generated by Django 4.1 on 2023-03-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_remove_instance_id_flavour_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Image", new_name="aws_image",),
    ]
