# Generated by Django 4.1 on 2023-03-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_remove_key_key_name_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="bill", name="bill_name",),
        migrations.RemoveField(model_name="bill", name="program",),
        migrations.RemoveField(model_name="bill", name="team",),
        migrations.DeleteModel(name="daily_usage",),
        migrations.DeleteModel(name="Bill",),
    ]
