# Generated by Django 4.1 on 2023-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_remove_bill_bill_name_remove_bill_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot_instance",
            name="flavor",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
