# Generated by Django 4.1 on 2023-03-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_alter_snapshot_instance_flavor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flavor", old_name="Ram_MB", new_name="Ram_GB",
        ),
    ]
