# Generated by Django 4.1 on 2023-03-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0068_rename_ram_mb_flavor_ram_gb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapshot_instance", old_name="Image", new_name="Image_aws",
        ),
        migrations.AddField(
            model_name="snapshot_instance",
            name="Image_op",
            field=models.CharField(default=4, max_length=64),
            preserve_default=False,
        ),
    ]
